export const datasecurite = {
    fr: [
    
{
    id: 39,
    question: "Question 1. Que signifie les fléches rouge ?",
    option1:"Un  fil Non-conforme ",
    option2:"Un  boîtier  Non-conforme ",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
    
},
{
    id: 40,
    question: "Question 2. Que signifie les fléches jaune ?",
    option1:"Un  fil Non-conforme ",
    option2:"Un  boîtier  Non-conforme ",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
    
},
{
    id: 41,
    question: "Question 3.  Respecte  les consignes de sécurité ?",
    option1:"Oui  ",
    option2:"Non",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 42,
    question: "Question 4. Respecte les consignes de sécurité?",
    option1:"Oui  ",
    option2:"Non",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 43,
    question: "Question 5. Respecte les consignes de sécurité?",
    option1:"Oui  ",
    option2:"Non",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 44,
    question: "Question 6. Respecte les consignes de sécurité?",
    option1:"Oui  ",
    option2:"Non",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 45,
    question: "Question 7. Respecte les consignes de sécurité?",
    option1:"Oui  ",
    option2:"Non",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 46,
    question: "3. Respecte les consignes de sécurité?",
    option1:"Oui  ",
    option2:"Non",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 47,
    question: "4. En cas d'un fil non-conforme  ",
    option1:"J'appelle la réparatrice pour faire le désenfichage   ",
    option2:"Je fais moi-même le désenfichage  ",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 48,
    question: "5. L'application de l'arrêt 1 défaut   ",
    option1:"Sur tous les défaut détectés    ",
    option2:"Sur les défauts détectés dans le montage   ",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 49,
    question: "6. Remplissage du carte Rouge ",
    type: 'input',
    hasInput: true,

}

    ],
    ar: [
        
        {
            id: 39,
            question: "ما هو اللون في المستطيل؟",
            option1: "أخضر",
            option2: "أحمر",
            option3: "أزرق",
            option4: "أصفر",
            option5: "آخر",
            ans: 2,
            type: 'multiple-choice',
            hasInput: false,
        },
        {
            id: 40,
            question: "ما هو اللون في المستطيل؟",
            option1: "أخضر",
            option2: "أحمر",
            option3: "أزرق",
            option4: "أصفر",
            option5: "آخر",
            ans: 2,
            type: 'multiple-choice',
            hasInput: false,
        },
        {
            id: 41,
            question: "ما هو اللون في المستطيل؟",
            option1: "أخضر",
            option2: "أحمر",
            option3: "أزرق",
            option4: "أصفر",
            option5: "آخر",
            ans: 2,
            type: 'multiple-choice',
            hasInput: false,
        },
        {
            id: 42,
            question: "ما هو اللون في المستطيل؟",
            option1: "أخضر",
            option2: "أحمر",
            option3: "أزرق",
            option4: "أصفر",
            option5: "آخر",
            ans: 2,
            type: 'multiple-choice',
            hasInput: false,
        },
        {
            id: 43,
            question: "ما هو اللون في المستطيل؟",
            option1: "أخضر",
            option2: "أحمر",
            option3: "أزرق",
            option4: "أصفر",
            option5: "آخر",
            ans: 2,
            type: 'multiple-choice',
            hasInput: false,
        },
        {
    id: 44,
    question: "Remplissage du carte Rouge ",
    type: 'input',
    hasInput: true,
},
{
    id: 45,
    question: "ما هو اللون في المستطيل؟",
    option1: "أخضر",
    option2: "أحمر",
    option3: "أزرق",
    option4: "أصفر",
    option5: "آخر",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 46,
    question: "ما هو اللون في المستطيل؟",
    option1: "أخضر",
    option2: "أحمر",
    option3: "أزرق",
    option4: "أصفر",
    option5: "آخر",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 47,
    question: "ما هو اللون في المستطيل؟",
    option1: "أخضر",
    option2: "أحمر",
    option3: "أزرق",
    option4: "أصفر",
    option5: "آخر",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 48,
    question: "ما هو اللون في المستطيل؟",
    option1: "أخضر",
    option2: "أحمر",
    option3: "أزرق",
    option4: "أصفر",
    option5: "آخر",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
    ]
}

    

