export const datamodule = {
    fr: [
    
{
    id: 33,
    question: "1. Dans quelle cas on remplie la carte Rouge",
    option1:"Un  fil Non-conforme ",
    option2:"Un  boîtier  Non-conforme ",
    option3:"Faisceau   Non-conforme ",
    option4:"Bottes de fils   Non-conforme ",
    option5:"Autre",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 34,
    question: "2. Quand je dois mettre la frette rouge",
    option1:"Un  fil Non-conforme  ",
    option2:"Un  boîtier  Non-conforme ",
    option3:"Faisceau   Non-conforme ",
    option4:"Bottes de fils   Non-conforme ",
    option5:"Autre",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 35,
    question: "3. Mettre dans l'ordre les étapes de TNC ",
    option1:"Identifier  ",
    option2:"Alerter ",
    option3:"Isoler  ",
    option4:"Détecter  ",
    option5:"Autre",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 36,
    question: "4. En cas d'un fil non-conforme  ",
    option1:"J'appelle la réparatrice pour faire le désenfichage   ",
    option2:"Je fais moi-même le désenfichage  ",
    option3:"J'informe le TS et je continue mon travail   ",
    option4:"Je fais l'arrêt 1 defaut et j'informe le TS  ",
    option5:"Autre",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 37,
    question: "5. L'application de l'arrêt 1 défaut   ",
    option1:"Sur tous les défaut détectés    ",
    option2:"Sur les défauts détectés dans le montage   ",
    option3:"Sur les défauts détectés dans la Zone coupe préparation  ",
    option4:"Sur les défauts détectés dans le montage   ",
    option5:"Autre",
    ans: 2,
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 38,
    question: "6. Remplissage du carte Rouge ",
    type: 'input',
    hasInput: true,

}

    ],
    ar: [
        
        {
            id: 33,
            question: "ما هو اللون في المستطيل؟",
            option1: "أخضر",
            option2: "أحمر",
            option3: "أزرق",
            option4: "أصفر",
            option5: "آخر",
            ans: 2,
            type: 'multiple-choice',
            hasInput: false,
        },
        {
            id: 34,
            question: "ما هو اللون في المستطيل؟",
            option1: "أخضر",
            option2: "أحمر",
            option3: "أزرق",
            option4: "أصفر",
            option5: "آخر",
            ans: 2,
            type: 'multiple-choice',
            hasInput: false,
        },
        {
            id: 35,
            question: "ما هو اللون في المستطيل؟",
            option1: "أخضر",
            option2: "أحمر",
            option3: "أزرق",
            option4: "أصفر",
            option5: "آخر",
            ans: 2,
            type: 'multiple-choice',
            hasInput: false,
        },
        {
            id: 36,
            question: "ما هو اللون في المستطيل؟",
            option1: "أخضر",
            option2: "أحمر",
            option3: "أزرق",
            option4: "أصفر",
            option5: "آخر",
            ans: 2,
            type: 'multiple-choice',
            hasInput: false,
        },
        {
            id: 37,
            question: "ما هو اللون في المستطيل؟",
            option1: "أخضر",
            option2: "أحمر",
            option3: "أزرق",
            option4: "أصفر",
            option5: "آخر",
            ans: 2,
            type: 'multiple-choice',
            hasInput: false,
        },
        {
    id: 38,
    question: "Remplissage du carte Rouge ",
    type: 'input',
    hasInput: true,

}
    ]
}

    

