export const data = {
  fr: [
    {
      id: 1,
      question: "Quelle est votre taille ?",
      ans: -1, // Pas de bonne réponse prédéfinie car la réponse sera saisie
      type: "input",
      hasInput: true,
    },
    {
      id: 2,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 2,
      type: "multiple-choice",
      image: "/assets/image/qst99.png",
      hasInput: false,
    },
    {
      id: 3,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 4,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 1,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 5,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 2,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 6,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 3,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 7,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 2,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 8,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 9,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 10,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 3,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 11,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 2,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 12,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 0,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 13,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 14,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 15,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 1,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 16,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 17,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 2,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 18,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 2,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 19,
      question: "Quelle est la couleur dans le rectangle ?",
      options: ["Vert", "Rouge", "Bleu", "Jaune", "Autre"],
      ans: 0,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 20,
      question: "Combien y a-t-il de carrés noirs ?",
      options: ["3", "4", "5", "6", "7"],
      ans: 0, // The correct answer is option 3 ("5")
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 21,
      question: "Combien y a-t-il de carrés bleu ?",
      options: ["3", "4", "5", "6", "7"],
      ans: 3,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 22,
      question: "Combien y a-t-il de carrés rouge ?",
      options: ["3", "4", "5", "6", "2"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 23,
      question: "Quelle est la valeur de cercle + carré * triangle ?",
      options: ["15", "20", "19", "14", "18"],
      ans: 2,
      image: "/../images/Qst22.png", // URL de l'image pour la question 23
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 24,
      question: "Quelle est la valeur de  carré ?",
      options: ["20", "6", "19", "12", "5"],
      ans: 2,
      image: "/../images/qst33.png", // URL de l'image pour la question 24
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 25,
      question: "Quelle est la valeur de  triangle ?",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: '/../images/qst44.png', // URL de l'image pour la question 25
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 26,
      question: "Quelle est la valeur de  cercle ?",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: "/@/images/qst55.png", // URL de l'image pour la question 25
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 27,
      question: "Quelle est la valeur ?",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: "/@/images/qst66.png", // URL de l'image pour la question 24
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 28,
      question: "Quelle est la valeur de vague?",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: "/@/images/qst77.png", // URL de l'image pour la question 24
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 29,
      question: "Quelle est la valeur de losange?",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: "/@/images/qst88.png", // URL de l'image pour la question 24
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 30,
      question: "Quelle est la valeur d'arc partiel'?",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: "/@/images/qst99.png", // URL de l'image pour la question 24
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 31,
      question: "Pourquoi voulez-vous travailler avec Leoni ?",
      type: "input",
      hasInput: true,
    },
    {
      id: 32,
      question: "Quel est votre objectif d'ici 3 ans ?",
      type: "input",
      hasInput: true,
    },
    {
      id: 33,
      question: "Cochez avec (.) le maximum de cercles en 30 secondes",
      type: "checkbox-grid",
      totalBoxes: 100,
      points: {
        minCoches: 70,
        maxPoints: 4,
        minPoints: 1,
      },
      hasInput: false,
    },
  ],
  ar: [
    {
      id: 1,
      question: "ما هو طولك؟",
      ans: -1,
      type: "input",
      hasInput: true,
    },
    {
      id: 2,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 2,
      type: "multiple-choice",
      image: "/assets/image/qst99.png",
      hasInput: false,
    },
    {
      id: 3,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 4,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 1,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 5,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 2,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 6,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 3,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 7,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 2,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 8,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 9,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 10,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 3,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 11,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 2,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 12,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 0,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 13,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 14,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 15,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 1,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 16,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 17,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 2,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 18,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 2,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 19,
      question: "ما هو اللون في المستطيل؟",
      options: ["أخضر", "أحمر", "أزرق", "أصفر", "آخر"],
      ans: 0,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 20,
      question: "كم عدد المربعات السوداء؟",
      options: ["3", "4", "5", "6", "7"],
      ans: 0,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 21,
      question: "كم عدد المربعات الزرقاء؟",
      options: ["3", "4", "5", "6", "7"],
      ans: 3,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 22,
      question: "كم عدد المربعات الحمراء؟",
      options: ["3", "4", "5", "6", "2"],
      ans: 4,
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 23,
      question: "ما هي قيمة دائرة + مربع * مثلث؟",
      options: ["15", "20", "19", "14", "18"],
      ans: 2,
      image: "/assets/image/Qst22.png",
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 24,
      question: "ما هي قيمة المربع؟",
      options: ["20", "6", "19", "12", "5"],
      ans: 2,
      image: "/assets/image/qst33.png",
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 25,
      question: "ما هي قيمة المثلث؟",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: "/assets/image/qst44.png",
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 26,
      question: "ما هي قيمة الدائرة؟",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: "/assets/image/qst55.png",
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 27,
      question: "ما هي القيمة؟",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: "/assets/image/qst66.png",
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 28,
      question: "ما هي قيمة الموجة؟",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: "/assets/image/qst77.png",
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 29,
      question: "ما هي قيمة المعين؟",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: "/assets/image/qst88.png",
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 30,
      question: "ما هي قيمة القوس الجزئي؟",
      options: ["16", "6", "19", "12", "5"],
      ans: 2,
      image: "/assets/image/qst99.png",
      type: "multiple-choice",
      hasInput: false,
    },
    {
      id: 31,
      question: "لماذا تريد العمل مع ليوني؟",
      type: "input",
      hasInput: true,
    },
    {
      id: 32,
      question: "ما هو هدفك خلال 3 سنوات؟",
      type: "input",
      hasInput: true,
    },
    {
      id: 33,
      question: "حدد (.) أكبر عدد ممكن من الدوائر في 30 ثانية",
      type: "checkbox-grid",
      totalBoxes: 100,
      points: {
        minCoches: 70,
        maxPoints: 4,
        minPoints: 1,
      },
      hasInput: false,
    },
  ],
};
