export const data = [
    {
        id:1,
        question: "Quelle est votre taille ?",
        ans: -1, // Pas de bonne réponse prédéfinie car la réponse sera saisie
        type: 'input',
        hasInput: true,
    },
    {
        
        id:2,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 2,
        type: 'multiple-choice',
        image: "/assets/image/qst99.PNG",
        hasInput: false,
    },
    {
        id:3,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 4,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:4,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 1,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:5,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 2,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:6,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 3,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:7,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 2,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:8,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 4,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:9,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 4,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:10,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 3,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:11,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 2,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:12,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 0,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:13,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 4,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:14,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 4,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:15,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 1,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:16,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 4,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:17,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 2,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:18,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 2,
        type: 'multiple-choice',
        hasInput: false,
    },
    {
        id:19,
        question: "Quelle est la couleur dans le rectangle ?",
        option1: "Vert", 
        option2:"Rouge", 
        option3:"Bleu", 
        option4:"Jaune",
        option5:"autre",
        ans: 0,
        type: 'multiple-choice',
        hasInput: false,
    },
    
    {
        id:20,    
        question: "Combien y a-t-il de carrés noirs ?",
            option1: "3",
            option2: "4",
            option3: "5",
            option4: "6",
            option5: "7",
            ans: 0 ,// The correct answer is option 3 ("5")
            type: 'multiple-choice',
            hasInput: false,
        },
    
    {
        id:21,    
        question: "Combien y a-t-il de carrés bleu ?",
            option1: "3",
            option2: "4",
            option3: "5",
            option4: "6",
            option5: "7",
            ans: 3, // The correct answer is option 3 ("5")
            type: 'multiple-choice',
            hasInput: false,
    },

    {
        id:22,
        question: "Combien y a-t-il de carrés rouge ?",
        option1: "3",
        option2: "4",
        option3: "5",
        option4: "6",
        option5: "2",
        ans: 4 ,
        type: 'multiple-choice',
        hasInput: false,
},

{
        id: 23,
        question: "Quelle est la valeur de cercle + carré * triangle ?",
        option1:"15",
        option2:"20",
        option3:"19",
        option4:"14",
        option5:"18",
        ans: 2,
        image: "/assets/image/Qst22.PNG" ,// URL de l'image pour la question 23
        type: 'multiple-choice',
        hasInput: false,
},

{
    id: 24,
    question: "Quelle est la valeur de  carré ?",
    option1:"20",
    option2:"6",
    option3:"19",
    option4:"12",
    option5:"5",
    ans: 2,
    image: "/assets/image/qst33.PNG" ,  // URL de l'image pour la question 24
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 24,
    question: "Quelle est la valeur de  triangle ?",
    option1:"16",
    option2:"6",
    option3:"19",
    option4:"12",
    option5:"5",
    ans: 2,
    image: "/assets/image/qst44.PNG" ,// URL de l'image pour la question 24
    type: 'multiple-choice',
    hasInput: false,
    
},
{
    id: 25,
    question: "Quelle est la valeur de  cercle ?",
    option1:"16",
    option2:"6",
    option3:"19",
    option4:"12",
    option5:"5",
    ans: 2,
    image: "/assets/image/qst55.PNG" ,// URL de l'image pour la question 25
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 26,
    question: "Quelle est la valeur ?",
    option1:"16",
    option2:"6",
    option3:"19",
    option4:"12",
    option5:"5",
    ans: 2,
    image: "/assets/image/qst66.PNG" ,// URL de l'image pour la question 24
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 27,
    question: "Quelle est la valeur de vague?",
    option1:"16",
    option2:"6",
    option3:"19",
    option4:"12",
    option5:"5",
    ans: 2,
    image: "/assets/image/qst77.PNG" ,// URL de l'image pour la question 24
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 28,
    question: "Quelle est la valeur de losange?",
    option1:"16",
    option2:"6",
    option3:"19",
    option4:"12",
    option5:"5",
    ans: 2,
    image: "/assets/image/qst88.PNG" ,// URL de l'image pour la question 24
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 29,
    question: "Quelle est la valeur d'arc partiel'?",
    option1:"16",
    option2:"6",
    option3:"19",
    option4:"12",
    option5:"5",
    ans: 2,
    image: "/assets/image/qst99.PNG" ,// URL de l'image pour la question 24
    type: 'multiple-choice',
    hasInput: false,
},
{
    id: 30,
    question: "Pourquoi voulez-vous travailler avec Leoni ?",
    type: 'input',
    hasInput: true,

}, {
    id: 31,
    question: "Quel est votre objectif d'ici 3 ans ?",
    type: 'input',
    hasInput: true,

}, {
    id: 32,
    question: "Cochez avec (.) le maximum de cercles en 30 secondes",
    type: 'checkbox-grid',
    totalBoxes: 100,
    points: {
        minCoches: 70,
        maxPoints: 4,
        minPoints: 1
    },
    hasInput: false,

}

    ]